apiVersion: v1
kind: Secret
metadata:
  name: scm-tool-gateway-secrets
  namespace: backend
type: Opaque
stringData:
  TOOL_GATEWAY_API_KEY: "DeciUwP4BF3/tHSptriTlhVw1lFw13PpC0PPqWMIExXdqQ9tL2N3fEYUI4Uv9hO+"
  TOOL_GATEWAY_API_KEYS: "DeciUwP4BF3/tHSptriTlhVw1lFw13PpC0PPqWMIExXdqQ9tL2N3fEYUI4Uv9hO+"
  ADS_SERVICE_IDENTIFIER: "shashidhar@smartcitymedia.us"
  ADS_SERVICE_PASSWORD: "Asterisk@123"
