apiVersion: v1
kind: Service
metadata:
  name: scm-tool-gateway
  namespace: backend
spec:
  selector:
    app: scm-tool-gateway
  ports:
    - name: http
      port: 80
      targetPort: 7070
  type: ClusterIP
